# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b846eea575dd271e1035758671d87709b9b0e9911c2344e08e3d1e69ee6983174791c643c2a68ccebf32af6a7754a7f396b36145b487832fe4bede29324cb0b

test:
  secret_key_base: fb54968e642b4f26cd80c68b4e958c5e2db97ee9f7f5c082fd017bb83694f7c5512798ded1a872895a2408063a887685f1ba6ccd4cd7ba7a6c93969b718521db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
